"use client"
import './globals.css';

import React from 'react';

import { Inter } from 'next/font/google';
import { useRouter } from 'next/navigation';
import { BiSearch } from 'react-icons/bi';
import { BsMinecartLoaded } from 'react-icons/bs';
import { HiOutlineMicrophone } from 'react-icons/hi';
import { IoMdNotificationsOutline } from 'react-icons/io';

import { verificationFieldsRound } from '@/constants/speceing';

import DashboardCSS from '../../style/Dashboard.module.css';
import MyServiceCSS from '../../style/MyServiceCSS.module.css';
import { UserStore } from '../../userStore';
import CustomerSidebar from '../Components/CustomerSidebar';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
    // const { user, setUser } = UserStore.useContainer();
  const router = useRouter();
//   console.log(user);
  return (
    <UserStore.Provider>
    <html lang="en">
       <body style={{background: 'black'}} className='text-white'>
        <div className="flex">
              <div style={{position: 'fixed', height: '100%'}} className='hidden lg:block'>
              <CustomerSidebar></CustomerSidebar>
              </div>
              
              <div className={`w-full lg:ml-[310px] ${DashboardCSS.sidebarBackground} lg:px-[48px] px-[10px] min-h-screen`}>
              <div>
                <div className="flex justify-between items-center pt-[24px]">
                    <div className={`flex items-center ${MyServiceCSS.tableRoomInput}`}>
                        <span className="mx-3">
                            <BiSearch color={'purple'} size={25}></BiSearch>
                        </span>
                        <input
                            style={{
                                borderRadius: verificationFieldsRound,
                                background: 'white',
                            }}
                            placeholder="Search for anything"
                            className="lg:w-[450px] w-full h-[45px] focus:outline-none border-0 pl-1 text-black"
                            type="text"
                            name=""
                            id=""
                        />
                        <span className="mx-3">
                            <HiOutlineMicrophone color={'purple'} size={25}></HiOutlineMicrophone>
                        </span>
                    </div>

                    <div className="lg:flex items-center hidden">

                        <span className='hover:cursor-pointer' onClick={()=> router.push('/cart')}><BsMinecartLoaded  color={'purple'}
                            size={25}></BsMinecartLoaded></span>

                        <span className='mx-[24px]'>
                            <IoMdNotificationsOutline
                                 color={'purple'}
                                size={30}
                            ></IoMdNotificationsOutline>
                        </span>
                        <i style={{color: 'purple', fontFamily: 'monospace'}} className='text-xl'>Be Raw, Buy Raw</i>
                        
                    </div>
                </div>
            </div>
              {children}
            </div>
          </div>
           
      </body>
    </html>
     </UserStore.Provider>
  )
}
