"use client"
import './globals.css';

import React from 'react';

import { Inter } from 'next/font/google';

import Footer from '@/Components/Footer';

import DashboardCSS from '../../style/Dashboard.module.css';
import {
  ProductsStore,
  UserStore,
} from '../../userStore';
import BeeRawNavbar from '../Components/BeeRawNavbar';
import CustomerSidebar from '../Components/CustomerSidebar';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <ProductsStore.Provider>
      <UserStore.Provider>
        <html lang="en">
          <body style={{ background: 'black', fontFamily: 'sans-serif' }} className='text-white'>
            <div className="flex">
              <div style={{ position: 'fixed', height: '100%' }} className='hidden lg:block'>
                <CustomerSidebar></CustomerSidebar>
              </div>

              <div className={`w-full lg:ml-[310px] ${DashboardCSS.sidebarBackground} lg:px-[48px] px-[10px] min-h-screen`}>
                <BeeRawNavbar></BeeRawNavbar>
                <div>
                  {children}
                </div>

                <div className='hidden lg:block md:block mb-4' data-aos="zoom-in-up">
                  <Footer></Footer>
                </div>
              </div>
            </div>

            <div className='block lg:hidden md:hidden' data-aos="zoom-in-up">
              <Footer></Footer>
            </div>
          </body>
        </html>
      </UserStore.Provider>
    </ProductsStore.Provider>
  )
}
